apiVersion: v1
kind: Service
metadata:
  name: mongo-back-service2
spec:
  selector:
    type: mongo-backend-emp
  type: ClusterIP
  ports:
  - port: 27017
    targetPort: 27017

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-back-deployment-emp
spec:
  selector:
    matchLabels:
      type: mongo-backend-emp
  template:
    metadata:
      labels:
        type: mongo-backend-emp
    spec:
      containers:
      - name: mongo-back-emp-container
        image: mongo
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: k8storage1
          mountPath: /data/
      volumes:
      - name: k8storage1
        persistentVolumeClaim:
          claimName: mongo-claim